// vuejs/src/App.vue
<template>
  <div class="terminal">
    <div class="terminal-header">
      <div class="terminal-buttons">
        <div class="btn close"></div>
        <div class="btn minimize"></div>
        <div class="btn maximize"></div>
      </div>
      <div class="terminal-title">
        <span class="status-indicator"></span>
        zsh 5.9 - secure session
      </div>
    </div>
    <div class="terminal-body" ref="terminalBody">
      <div v-for="(line, index) in lines" :key="index" class="line" v-html="line.content"></div>
      <div v-if="currentStep === 'username'" class="input-line">
        <span class="prompt">login:</span>
        <input
          ref="inputRef"
          type="text"
          class="input-field"
          v-model="currentCommand"
          @keypress="handleKeyPress"
          placeholder="Entrez votre nom d'utilisateur"
        />
        <span class="cursor" :style="{ display: currentCommand ? 'none' : 'inline-block' }"></span>
      </div>
      <div v-else-if="currentStep === 'password'" class="input-line">
        <span class="prompt">password:</span>
        <input
          ref="inputRef"
          type="password"
          class="input-field"
          v-model="currentCommand"
          @keypress="handleKeyPress"
          placeholder=""
        />
        <span class="cursor" :style="{ display: currentCommand ? 'none' : 'inline-block' }"></span>
      </div>
      <div v-else-if="currentStep === 'main'" class="input-line">
        <span class="prompt user">{{ username }}@secure-server:~$</span>
        <input
          ref="inputRef"
          type="text"
          class="input-field"
          v-model="currentCommand"
          @keypress="handleKeyPress"
          placeholder="Tapez 'help' pour voir les commandes disponibles"
        />
        <span class="cursor" :style="{ display: currentCommand ? 'none' : 'inline-block' }"></span>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, onMounted, nextTick } from 'vue';

const lines = ref([]);
const currentStep = ref('init');
const username = ref('');
const password = ref('');
const isProcessing = ref(false);
const currentCommand = ref('');
const terminalBody = ref(null);
const inputRef = ref(null);

onMounted(async () => {
  await init();
});

const init = async () => {
  await showWelcome();
  await delay(800);
  await showSystemInfo();
  await delay(500);
  await startLoginProcess();
};

const showWelcome = async () => {
  const asciiArt = `    ███████╗███████╗██╗  ██╗    ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗     
    ╚══███╔╝██╔════╝██║  ██║    ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║     
      ███╔╝ ███████╗███████║       ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║     
     ███╔╝  ╚════██║██╔══██║       ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║     
    ███████╗███████║██║  ██║       ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗
    ╚══════╝╚══════╝╚═╝  ╚═╝       ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝`;

  addLine(`<div class="ascii-art">${asciiArt}</div>`);
  await delay(500);
  addLine('<span class="success">Welcome to SecureShell Terminal v2.1.0</span>');
  await delay(300);
  addLine('<span class="output">Initializing secure connection...</span>');

  addLine('<div class="progress-bar"><div class="progress-fill" style="width: 0%;" id="progress"></div></div>');
  await nextTick();
  const progress = document.getElementById('progress');
  if (progress) {
    for (let i = 0; i <= 100; i += 10) {
      progress.style.width = i + '%';
      await delay(50);
    }
  }

  await delay(200);
  addLine('<span class="success">✓ Connection secured</span>');
};

const showSystemInfo = async () => {
  const now = new Date();
  const systemInfo = `
    <div class="system-info">
      <strong>System Information</strong><br>
      Hostname: <span class="highlight">secure-server.dev</span><br>
      IP: <span class="highlight">192.168.1.100</span><br>
      Last login: ${now.toLocaleDateString()} ${now.toLocaleTimeString()}<br>
      Shell: <span class="highlight">zsh 5.9</span>
    </div>
  `;
  addLine(systemInfo);
};

const startLoginProcess = async () => {
  await delay(500);
  addLine('<span class="warning">Authentication required for secure access</span>');
  await delay(300);
  currentStep.value = 'username';
  await nextTick(() => focusInput());
};

const addLine = (content) => {
  lines.value.push({ content });
  scrollToBottom();
};

const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

const scrollToBottom = async () => {
  await nextTick();
  if (terminalBody.value) {
    terminalBody.value.scrollTop = terminalBody.value.scrollHeight;
  }
};

const handleKeyPress = async (e) => {
  if (e.key === 'Enter' && !isProcessing.value) {
    isProcessing.value = true;
    const value = currentCommand.value.trim();
    if (currentStep.value === 'username') {
      addLine(`<span class="prompt">login:</span> <span class="command">${escapeHtml(value)}</span>`);
      if (!value) {
        addLine('<span class="error">Username cannot be empty</span>');
        isProcessing.value = false;
        currentCommand.value = '';
        await nextTick(() => focusInput());
        return;
      }
      username.value = value;
      addLine(`<span class="output">Hello <span class="highlight">${escapeHtml(username.value)}</span></span>`);
      await delay(300);
      currentStep.value = 'password';
      currentCommand.value = '';
    } else if (currentStep.value === 'password') {
      addLine(`<span class="prompt">password:</span> <span class="command">${'*'.repeat(currentCommand.value.length)}</span>`);
      if (!value) {
        addLine('<span class="error">Password cannot be empty</span>');
        isProcessing.value = false;
        currentCommand.value = '';
        await nextTick(() => focusInput());
        return;
      }
      password.value = value;
      await authenticateUser();
      currentCommand.value = '';
    } else if (currentStep.value === 'main') {
      addLine(`<span class="prompt user">${escapeHtml(username.value)}@secure-server:~$</span> <span class="command">${escapeHtml(value)}</span>`);
      if (value) {
        await executeCommand(value);
      }
      currentCommand.value = '';
    }
    isProcessing.value = false;
    await nextTick(() => focusInput());
  }
};

const authenticateUser = async () => {
  addLine('<span class="output">Authenticating<span class="loading-dots"></span></span>');
  await delay(2000);
  const success = Math.random() > 0.1;
  if (success) {
    await showSuccessLogin();
  } else {
    await showFailedLogin();
  }
};

const showSuccessLogin = async () => {
  addLine('<span class="success">✓ Authentication successful</span>');
  await delay(500);
  addLine('<span class="success">✓ Generating secure session</span>');
  await delay(300);
  addLine('<span class="success">✓ Loading user environment</span>');
  await delay(500);

  const welcomeBanner = `
    <div class="welcome-banner">
      <h3 style="color: var(--accent); margin-bottom: 12px;">🎉 Welcome ${escapeHtml(username.value)}!</h3>
      <p style="color: var(--text-secondary); margin-bottom: 8px;">You have successfully logged into the secure system</p>
      <p style="color: var(--text-muted); font-size: 12px;">Session ID: ${Math.random().toString(36).substr(2, 9).toUpperCase()}</p>
      <p style="color: var(--text-muted); font-size: 12px;">Login time: ${new Date().toLocaleString()}</p>
    </div>
  `;
  addLine(welcomeBanner);
  await delay(800);
  currentStep.value = 'main';
  await nextTick(() => focusInput());
};

const showFailedLogin = async () => {
  addLine('<span class="error">✗ Authentication failed</span>');
  await delay(300);
  addLine('<span class="error">Invalid username or password</span>');
  await delay(500);
  addLine('<span class="warning">Please try again...</span>');
  await delay(1000);
  username.value = '';
  password.value = '';
  currentStep.value = 'username';
  await nextTick(() => focusInput());
};

const executeCommand = async (command) => {
  const cmd = command.toLowerCase();
  switch (cmd) {
    case 'help':
      const helpText = `
        <div style="margin: 12px 0; color: var(--text-secondary);">
          <strong style="color: var(--accent);">Available Commands:</strong><br>
          <span class="highlight">help</span> - Show this help message<br>
          <span class="highlight">whoami</span> - Display current user<br>
          <span class="highlight">date</span> - Show current date and time<br>
          <span class="highlight">pwd</span> - Show current directory<br>
          <span class="highlight">clear</span> - Clear terminal screen<br>
          <span class="highlight">logout</span> or <span class="highlight">exit</span> - End session
        </div>
      `;
      addLine(helpText);
      break;
    case 'whoami':
      addLine(`<span class="output">${escapeHtml(username.value)}</span>`);
      break;
    case 'date':
      addLine(`<span class="output">${new Date().toString()}</span>`);
      break;
    case 'pwd':
      addLine(`<span class="output">/home/${escapeHtml(username.value)}</span>`);
      break;
    case 'logout':
    case 'exit':
      addLine('<span class="warning">Logging out...</span>');
      await delay(1000);
      addLine('<span class="success">Session terminated. Goodbye!</span>');
      await delay(2000);
      // Simuler reload
      location.reload();
      return;
    case 'clear':
      lines.value = [];
      return;
    default:
      addLine(`<span class="error">Command not found: ${escapeHtml(command)}</span>`);
      addLine(`<span class="output">Type 'help' to see available commands</span>`);
  }
};

const focusInput = () => {
  if (inputRef.value) {
    inputRef.value.focus();
  }
};

const escapeHtml = (text) => {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
};
</script>

// react/src/App.jsx
/* eslint-disable react-hooks/exhaustive-deps */
import React, { useEffect, useState, useRef } from "react";
import "./assets/style.css";

const App = () => {
    const [lines, setLines] = useState([]);
    const [currentStep, setCurrentStep] = useState("init");
    const [username, setUsername] = useState("");
    const [_password, setPassword] = useState("");
    const [isProcessing, setIsProcessing] = useState(false);
    const [currentCommand, setCurrentCommand] = useState("");
    const terminalBodyRef = useRef(null);
    const inputRef = useRef(null);

    useEffect(() => {
        init();
    }, []);

    const init = async () => {
        await showWelcome();
        await delay(800);
        await showSystemInfo();
        await delay(500);
        await startLoginProcess();
    };

    const showWelcome = async () => {
        const asciiArt = `    ███████╗███████╗██╗  ██╗    ████████╗███████╗██████╗ ███╗   ███╗██╗███╗   ██╗ █████╗ ██╗     
    ╚══███╔╝██╔════╝██║  ██║    ╚══██╔══╝██╔════╝██╔══██╗████╗ ████║██║████╗  ██║██╔══██╗██║     
      ███╔╝ ███████╗███████║       ██║   █████╗  ██████╔╝██╔████╔██║██║██╔██╗ ██║███████║██║     
     ███╔╝  ╚════██║██╔══██║       ██║   ██╔══╝  ██╔══██╗██║╚██╔╝██║██║██║╚██╗██║██╔══██║██║     
    ███████╗███████║██║  ██║       ██║   ███████╗██║  ██║██║ ╚═╝ ██║██║██║ ╚████║██║  ██║███████╗
    ╚══════╝╚══════╝╚═╝  ╚═╝       ╚═╝   ╚══════╝╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═══╝╚═╝  ╚═╝╚══════╝`;

        addLine(<div className="ascii-art">{asciiArt}</div>);
        await delay(500);
        addLine(
            <span className="success">Welcome to SecureShell Terminal v2.1.0</span>
        );
        await delay(300);
        addLine(<span className="output">Initializing secure connection...</span>);

        // Progress bar simulation
        addLine(
            <div className="progress-bar">
                <div
                    className="progress-fill"
                    style={{ width: "0%" }}
                    id="progress"
                ></div>
            </div>
        );
        const progress = document.getElementById("progress");
        if (progress) {
            for (let i = 0; i <= 100; i += 10) {
                progress.style.width = i + "%";
                await delay(50);
            }
        }

        await delay(200);
        addLine(<span className="success">✓ Connection secured</span>);
    };

    const showSystemInfo = async () => {
        const now = new Date();
        addLine(
            <div className="system-info">
                <strong>System Information</strong>
                <br />
                Hostname: <span className="highlight">secure-server.dev</span>
                <br />
                IP: <span className="highlight">192.168.1.100</span>
                <br />
                Last login: {now.toLocaleDateString()} {now.toLocaleTimeString()}
                <br />
                Shell: <span className="highlight">zsh 5.9</span>
            </div>
        );
    };

    const startLoginProcess = async () => {
        await delay(500);
        addLine(
            <span className="warning">Authentication required for secure access</span>
        );
        await delay(300);
        setCurrentStep("username");
    };

    const addLine = (content) => {
        setLines((prev) => [
            ...prev,
            { key: Date.now() + Math.random(), content, type: "line" },
        ]);
        scrollToBottom();
    };

    const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

    const scrollToBottom = () => {
        if (terminalBodyRef.current) {
            terminalBodyRef.current.scrollTop = terminalBodyRef.current.scrollHeight;
        }
    };

    const handleInput = (e) => {
        setCurrentCommand(e.target.value);
    };

    const handleKeyPress = async (e) => {
        if (e.key === "Enter" && !isProcessing) {
            setIsProcessing(true);
            if (currentStep === "username") {
                if (!currentCommand.trim()) {
                    addLine(<span className="error">Username cannot be empty</span>);
                    setIsProcessing(false);
                    return;
                }
                setUsername(currentCommand.trim());
                addLine(
                    <span className="output">
                        Hello <span className="highlight">{currentCommand.trim()}</span>
                    </span>
                );
                await delay(300);
                setCurrentStep("password");
                setCurrentCommand("");
            } else if (currentStep === "password") {
                if (!currentCommand.trim()) {
                    addLine(<span className="error">Password cannot be empty</span>);
                    setIsProcessing(false);
                    return;
                }
                setPassword(currentCommand);
                await authenticateUser();
            } else if (currentStep === "main") {
                await executeCommand(currentCommand.trim());
            }
            setIsProcessing(false);
        }
    };

    const authenticateUser = async () => {
        addLine(<span className="output">Authenticating...</span>);
        await delay(2000);
        const success = Math.random() > 0.1;
        if (success) {
            await showSuccessLogin();
        } else {
            await showFailedLogin();
        }
    };

    const showSuccessLogin = async () => {
        addLine(<span className="success">✓ Authentication successful</span>);
        await delay(500);
        addLine(<span className="success">✓ Generating secure session</span>);
        await delay(300);
        addLine(<span className="success">✓ Loading user environment</span>);
        await delay(500);

        const welcomeBanner = (
            <div className="welcome-banner">
                <h3 style={{ color: "var(--accent)", marginBottom: "12px" }}>
                    🎉 Welcome {username}!
                </h3>
                <p style={{ color: "var(--text-secondary)", marginBottom: "8px" }}>
                    You have successfully logged into the secure system
                </p>
                <p style={{ color: "var(--text-muted)", fontSize: "12px" }}>
                    Session ID: {Math.random().toString(36).substr(2, 9).toUpperCase()}
                </p>
                <p style={{ color: "var(--text-muted)", fontSize: "12px" }}>
                    Login time: {new Date().toLocaleString()}
                </p>
            </div>
        );
        addLine(welcomeBanner);
        await delay(800);
        setCurrentStep("main");
    };

    const showFailedLogin = async () => {
        addLine(<span className="error">✗ Authentication failed</span>);
        await delay(300);
        addLine(<span className="error">Invalid username or password</span>);
        await delay(500);
        addLine(<span className="warning">Please try again...</span>);
        await delay(1000);
        setUsername("");
        setPassword("");
        setCurrentStep("username");
    };

    const executeCommand = async (command) => {
        const cmd = command.toLowerCase();
        switch (cmd) {
            case "help":
                { const helpText = (
                    <div style={{ margin: "12px 0", color: "var(--text-secondary)" }}>
                        <strong style={{ color: "var(--accent)" }}>
                            Available Commands:
                        </strong>
                        <br />
                        <span className="highlight">help</span> - Show this help message
                        <br />
                        <span className="highlight">whoami</span> - Display current user
                        <br />
                        <span className="highlight">date</span> - Show current date and time
                        <br />
                        <span className="highlight">pwd</span> - Show current directory
                        <br />
                        <span className="highlight">clear</span> - Clear terminal screen
                        <br />
                        <span className="highlight">logout</span> or{" "}
                        <span className="highlight">exit</span> - End session
                    </div>
                );
                addLine(helpText);
                break; }
            case "whoami":
                addLine(<span className="output">{username}</span>);
                break;
            case "date":
                addLine(<span className="output">{new Date().toString()}</span>);
                break;
            case "pwd":
                addLine(<span className="output">/home/{username}</span>);
                break;
            case "logout":
            case "exit":
                addLine(<span className="warning">Logging out...</span>);
                await delay(1000);
                addLine(<span className="success">Session terminated. Goodbye!</span>);
                await delay(2000);
                // Simuler reload
                window.location.reload();
                return;
            case "clear":
                setLines([]);
                return;
            default:
                addLine(<span className="error">Command not found: {command}</span>);
                addLine(
                    <span className="output">Type 'help' to see available commands</span>
                );
        }
        setCurrentCommand("");
    };

    useEffect(() => {
        if (inputRef.current) {
            inputRef.current.focus();
        }
    }, [currentStep, lines]);

    const renderInput = () => {
        if (currentStep === "username") {
            return (
                <div className="input-line">
                    <span className="prompt">login:</span>
                    <input
                        ref={inputRef}
                        type="text"
                        className="input-field"
                        value={currentCommand}
                        onChange={handleInput}
                        onKeyPress={handleKeyPress}
                        placeholder="Entrez votre nom d'utilisateur"
                    />
                    <span
                        className="cursor"
                        style={{ display: currentCommand ? "none" : "inline-block" }}
                    ></span>
                </div>
            );
        } else if (currentStep === "password") {
            return (
                <div className="input-line">
                    <span className="prompt">password:</span>
                    <input
                        ref={inputRef}
                        type="password"
                        className="input-field"
                        value={currentCommand}
                        onChange={handleInput}
                        onKeyPress={handleKeyPress}
                        placeholder=""
                    />
                    <span
                        className="cursor"
                        style={{ display: currentCommand ? "none" : "inline-block" }}
                    ></span>
                </div>
            );
        } else if (currentStep === "main") {
            return (
                <div className="input-line">
                    <span className="prompt user">{username}@secure-server:~$</span>
                    <input
                        ref={inputRef}
                        type="text"
                        className="input-field"
                        value={currentCommand}
                        onChange={handleInput}
                        onKeyPress={handleKeyPress}
                        placeholder="Tapez 'help' pour voir les commandes disponibles"
                    />
                    <span
                        className="cursor"
                        style={{ display: currentCommand ? "none" : "inline-block" }}
                    ></span>
                </div>
            );
        }
        return null;
    };

    return (
        <div className="terminal">
            <div className="terminal-header">
                <div className="terminal-buttons">
                    <div className="btn close"></div>
                    <div className="btn minimize"></div>
                    <div className="btn maximize"></div>
                </div>
                <div className="terminal-title">
                    <span className="status-indicator"></span>
                    zsh 5.9 - secure session
                </div>
            </div>
            <div className="terminal-body" ref={terminalBodyRef}>
                {lines.map((line) => (
                    <div key={line.key} className="line">
                        {line.content}
                    </div>
                ))}
                {renderInput()}
            </div>
        </div>
    );
};

export default App;
